[package]
name = "weather"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.2.2"
reqwest = { version = "0.11.18", features = ["blocking"] }
serde_json = "1.0.105"
